version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: "on-failure"
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD:
      POSTGRES_PORT:
      POSTGRES_USER:
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - net

volumes:
  postgres-data:

networks:
  net:
